// Usuarios CRUD
export const AGREGAR_USUARIO = 'AGREGAR_USUARIO';
export const AGREGAR_USUARIO_EXITO = 'AGREGAR_USUARIO_EXITO';
export const AGREGAR_USUARIO_ERROR = 'AGREGAR_USUARIO_ERROR';

export const DESCARGA_USUARIOS = 'DESCARGA_USUARIOS';
export const DESCARGA_USUARIOS_EXITO = 'DESCARGA_USUARIOS_EXITO';
export const DESCARGA_USUARIOS_ERROR = 'DESCARGA_USUARIOS_ERROR';

export const ELIMINAR_USUARIO = 'ELIMINAR_USUARIO';
export const ELIMINAR_USUARIO_EXITO = 'ELIMINAR_USUARIO_EXITO';
export const ELIMINAR_USUARIO_ERROR = 'ELIMINAR_USUARIO_ERROR';

export const EDITAR_USUARIO = 'EDITAR_USUARIO';
export const COMENZAR_EDICION_USUARIO = 'COMENZAR_EDICION_USUARIO';
export const EDITAR_USUARIO_EXITO = 'EDITAR_USUARIO_EXITO';
export const EDITAR_USUARIO_ERROR = 'EDITAR_USUARIO_ERROR';

// Clientes CRUD
export const AGREGAR_CLIENTE = 'AGREGAR_CLIENTE';
export const AGREGAR_CLIENTE_EXITO = 'AGREGAR_CLIENTE_EXITO';
export const AGREGAR_CLIENTE_ERROR = 'AGREGAR_CLIENTE_ERROR';

export const ELIMINAR_CLIENTE =       'ELIMINAR_CLIENTE';
export const ELIMINAR_CLIENTE_EXITO = 'ELIMINAR_CLIENTE_EXITO';
export const ELIMINAR_CLIENTE_ERROR = 'ELIMINAR_CLIENTE_ERROR';

export const DESCARGA_CLIENTES = 'DESCARGA_CLIENTES';
export const DESCARGA_CLIENTES_EXITO = 'DESCARGA_CLIENTES_EXITO';
export const DESCARGA_CLIENTES_ERROR = 'DESCARGA_CLIENTES_ERROR';

export const EDITAR_CLIENTE = 'EDITAR_CLIENTE';
export const EDITAR_CLIENTE_EXITO = 'EDITAR_CLIENTE_EXITO';
export const EDITAR_CLIENTE_ERROR = 'EDITAR_CLIENTE_ERROR';

// Editar avisos
export const EDITAR_AVISO = 'EDITAR_AVISO';
export const EDITAR_AVISO_EXITO = 'EDITAR_AVISO_EXITO';
export const EDITAR_AVISO_ERROR = 'EDITAR_AVISO_ERROR';
export const COMENZAR_EDICION_CLIENTE = 'COMENZAR_EDICION_CLIENTE';

export const types = {

    login:  '[Auth] Login',
    logout: '[Auth] Logout',
    errorFound: '[Auth] Error found',
    startLoading: '[Auth] Start loading',
}